# Generated by Django 5.2.17 on 2026-09-12 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='chave')),
                ('value', models.JSONField(blank=True, null=True, verbose_name='valor')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='descrição')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'configuração',
                'verbose_name_plural': 'configurações',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('slug', models.SlugField(choices=[('sobre', 'Sobre o jornal'), ('privacidade', 'Privacidade'), ('colaborar', 'Como participar')], max_length=32, unique=True, verbose_name='página')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('lead', models.CharField(blank=True, max_length=240, verbose_name='linha fina')),
                ('body', models.TextField(blank=True, help_text='Separe parágrafos com uma linha em branco.', verbose_name='texto')),
                ('is_published', models.BooleanField(default=True, help_text='Desmarque para tirar a página do ar sem apagar o texto.', verbose_name='publicada')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizada por')),
            ],
            options={
                'verbose_name': 'página institucional',
                'verbose_name_plural': 'páginas institucionais',
                'ordering': ['slug'],
            },
        ),
    ]
