# Generated by Django 5.2.17 on 2026-09-15 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_staticpage_editor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Entrada no sistema"),
                            ("user_created", "Conta criada"),
                            ("role_changed", "Papel alterado"),
                            ("user_deactivated", "Conta desativada"),
                            ("user_reactivated", "Conta reativada"),
                            ("user_anonymized", "Conta anonimizada"),
                            ("data_exported", "Dados exportados"),
                            ("deletion_requested", "Exclusão pedida"),
                            ("access_link_created", "Link de acesso gerado"),
                            ("setting_changed", "Configuração alterada"),
                            ("media_deleted", "Imagem apagada"),
                            ("credit_anonymized", "Crédito de aluno anonimizado"),
                            ("articles_archived", "Publicações arquivadas em massa"),
                            ("reviewer_reassigned", "Revisor trocado em massa"),
                            ("featured_changed", "Destaques da home alterados"),
                            ("page_published", "Página institucional posta no ar"),
                            ("page_unpublished", "Página institucional tirada do ar"),
                        ],
                        db_index=True,
                        max_length=24,
                        verbose_name="ação",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(blank=True, max_length=40, verbose_name="tipo do alvo"),
                ),
                (
                    "target_id",
                    models.CharField(blank=True, max_length=64, verbose_name="id do alvo"),
                ),
                ("changes", models.JSONField(blank=True, default=dict, verbose_name="detalhes")),
                ("ip_hash", models.CharField(blank=True, max_length=64, verbose_name="IP (hash)")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="quando"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vazio quando a ação veio de um comando no servidor.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="quem fez",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de auditoria",
                "verbose_name_plural": "auditoria",
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["actor", "created_at"], name="core_auditl_actor_i_41600a_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_id"], name="core_auditl_target__6c66b3_idx"
                    ),
                ],
            },
        ),
    ]
