# Generated by Django 5.2.17 on 2026-09-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_acao_cadastro_proprio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='smtp.gmail.com', max_length=200, verbose_name='servidor de saída (SMTP)')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='porta')),
                ('security', models.CharField(choices=[('tls', 'STARTTLS (porta 587, o padrão do Gmail)'), ('ssl', 'SSL/TLS direto (porta 465)'), ('none', 'Nenhuma (só para testes na rede interna)')], default='tls', max_length=8, verbose_name='segurança')),
                ('username', models.CharField(blank=True, help_text='No Gmail, o próprio endereço. Os e-mails saem com este remetente.', max_length=254, verbose_name='usuário (e-mail que envia)')),
                ('password_encrypted', models.TextField(blank=True, editable=False)),
                ('from_name', models.CharField(blank=True, help_text='Vazio usa o nome do site.', max_length=80, verbose_name='nome do remetente')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'e-mail de envio',
                'verbose_name_plural': 'e-mail de envio',
            },
        ),
    ]
