# Generated by Django 5.2.17 on 2026-09-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contas_aprovacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Entrada no sistema'), ('user_created', 'Conta criada'), ('user_signed_up', 'Cadastro próprio'), ('user_approved', 'Conta aprovada'), ('user_rejected', 'Cadastro recusado'), ('password_reset', 'Senha redefinida por código'), ('role_changed', 'Papel alterado'), ('user_deactivated', 'Conta desativada'), ('user_reactivated', 'Conta reativada'), ('user_anonymized', 'Conta anonimizada'), ('data_exported', 'Dados exportados'), ('deletion_requested', 'Exclusão pedida'), ('access_link_created', 'Link de acesso gerado'), ('setting_changed', 'Configuração alterada'), ('media_deleted', 'Imagem apagada'), ('credit_anonymized', 'Crédito de aluno anonimizado'), ('articles_archived', 'Publicações arquivadas em massa'), ('reviewer_reassigned', 'Revisor trocado em massa'), ('featured_changed', 'Destaques da home alterados'), ('page_published', 'Página institucional posta no ar'), ('page_unpublished', 'Página institucional tirada do ar'), ('comment_moderated', 'Comentário público moderado')], db_index=True, max_length=24, verbose_name='ação'),
        ),
    ]
