# Generated by Django 5.2.17 on 2026-09-15 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0006_search'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_key', models.UUIDField(blank=True, null=True, verbose_name='código anônimo')),
                ('kind', models.CharField(choices=[('interesting', 'Interessante'), ('learned', 'Aprendi algo'), ('liked', 'Gostei'), ('congrats', 'Parabéns')], max_length=16, verbose_name='tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='publications.article', verbose_name='publicação')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'reação',
                'verbose_name_plural': 'reações',
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('article', 'user'), name='reaction_unique_user'), models.UniqueConstraint(condition=models.Q(('anon_key__isnull', False)), fields=('article', 'anon_key'), name='reaction_unique_anon_key'), models.CheckConstraint(condition=models.Q(models.Q(('anon_key__isnull', True), ('user__isnull', False)), models.Q(('anon_key__isnull', False), ('user__isnull', True)), _connector='OR'), name='reaction_user_or_anon_key')],
            },
        ),
    ]
