# Generated by Django 5.2.17 on 2026-09-15 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
        ('publications', '0006_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_key', models.CharField(max_length=64, verbose_name='leitor (hash)')),
                ('day', models.DateField(verbose_name='dia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrada em')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='publications.article', verbose_name='publicação')),
            ],
            options={
                'verbose_name': 'leitura',
                'verbose_name_plural': 'leituras',
                'indexes': [models.Index(fields=['day'], name='article_read_day')],
                'constraints': [models.UniqueConstraint(fields=('article', 'viewer_key', 'day'), name='article_read_unique_per_day')],
            },
        ),
    ]
