# Generated by Django 5.2.17 on 2026-09-15 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_article_read'),
        ('publications', '0006_search'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=60, verbose_name='nome')),
                ('body', models.TextField(max_length=1000, verbose_name='comentário')),
                ('status', models.CharField(choices=[('pending', 'Aguardando aprovação'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10, verbose_name='situação')),
                ('anon_key', models.UUIDField(blank=True, null=True, verbose_name='código anônimo')),
                ('ip_hash', models.CharField(blank=True, max_length=64, verbose_name='IP (hash)')),
                ('had_links', models.BooleanField(default=False, verbose_name='tinha links')),
                ('reply_body', models.TextField(blank=True, max_length=1000, verbose_name='resposta')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='respondido em')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='moderado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='publications.article', verbose_name='publicação')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_comments', to=settings.AUTH_USER_MODEL, verbose_name='moderado por')),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_replies', to=settings.AUTH_USER_MODEL, verbose_name='respondido por')),
            ],
            options={
                'verbose_name': 'comentário público',
                'verbose_name_plural': 'comentários públicos',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['article', 'status', 'created_at'], name='comment_article_status'), models.Index(fields=['status', 'created_at'], name='comment_status_created')],
            },
        ),
    ]
