# Generated by Django 5.2.17 on 2026-09-12 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0003_article_last_edited_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('review_requested', 'Revisão pedida'), ('changes_requested', 'Alterações sugeridas'), ('approved', 'Revisão aprovada'), ('published_by_other', 'Publicado por outra pessoa'), ('edited_by_other', 'Editado por outra pessoa'), ('archived_by_other', 'Arquivado por outra pessoa'), ('comment_pending', 'Comentário aguardando'), ('review_stale', 'Revisão parada'), ('system', 'Sistema')], max_length=24, verbose_name='tipo')),
                ('message', models.CharField(max_length=200, verbose_name='mensagem')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='endereço')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lida em')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='quem fez')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='publications.article', verbose_name='publicação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinatário')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'read_at', '-updated_at'], name='editorial_n_user_id_032eba_idx')],
            },
        ),
    ]
