# Generated by Django 5.2.17 on 2026-09-14 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0001_initial'),
        ('publications', '0004_alter_article_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('status_change', 'Mudança de estado'), ('reviewer_assigned', 'Revisor designado'), ('reviewer_removed', 'Revisão cancelada ou recusada'), ('approved', 'Revisão aprovada'), ('contributor_changed', 'Créditos alterados'), ('edited_after_publish', 'Editado depois de publicado'), ('edited_by_third_party', 'Editado por terceiro'), ('credit_anonymized', 'Crédito anonimizado')], max_length=24, verbose_name='tipo')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='estado anterior')),
                ('to_status', models.CharField(blank=True, max_length=20, verbose_name='estado novo')),
                ('note', models.TextField(blank=True, verbose_name='nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='quando')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_events', to=settings.AUTH_USER_MODEL, verbose_name='quem fez')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='publications.article', verbose_name='publicação')),
            ],
            options={
                'verbose_name': 'evento editorial',
                'verbose_name_plural': 'eventos editoriais',
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['article', 'created_at'], name='editorial_e_article_e820ff_idx'), models.Index(fields=['actor', 'created_at'], name='editorial_e_actor_i_3ebf70_idx')],
            },
        ),
    ]
