# Generated by Django 5.2.17 on 2026-09-14 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0002_editorialevent'),
        ('publications', '0004_alter_article_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialevent',
            name='kind',
            field=models.CharField(choices=[('status_change', 'Mudança de estado'), ('reviewer_assigned', 'Revisor designado'), ('reviewer_removed', 'Revisão cancelada ou recusada'), ('approved', 'Revisão aprovada'), ('contributor_changed', 'Créditos alterados'), ('edited_after_publish', 'Editado depois de publicado'), ('edited_by_third_party', 'Editado por terceiro'), ('credit_anonymized', 'Crédito anonimizado'), ('comment_added', 'Comentário na revisão'), ('comment_replied', 'Resposta a comentário'), ('comment_resolved', 'Comentário resolvido'), ('comment_reopened', 'Comentário reaberto')], max_length=24, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('review_requested', 'Revisão pedida'), ('changes_requested', 'Alterações sugeridas'), ('approved', 'Revisão aprovada'), ('published_by_other', 'Publicado por outra pessoa'), ('edited_by_other', 'Editado por outra pessoa'), ('archived_by_other', 'Arquivado por outra pessoa'), ('comment_pending', 'Comentário aguardando'), ('review_comment', 'Comentário na revisão'), ('review_stale', 'Revisão parada'), ('system', 'Sistema')], max_length=24, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='EditorialComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000, verbose_name='comentário')),
                ('anchor_text', models.CharField(blank=True, max_length=300, verbose_name='trecho')),
                ('anchor_prefix', models.CharField(blank=True, max_length=40, verbose_name='antes do trecho')),
                ('anchor_suffix', models.CharField(blank=True, max_length=40, verbose_name='depois do trecho')),
                ('anchor_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='início do trecho')),
                ('anchor_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='fim do trecho')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('resolved', 'Resolvido')], default='open', max_length=10, verbose_name='situação')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolvido em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_comments', to='publications.article', verbose_name='publicação')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_comments', to=settings.AUTH_USER_MODEL, verbose_name='quem escreveu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='editorial.editorialcomment', verbose_name='responde a')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='resolvido por')),
            ],
            options={
                'verbose_name': 'comentário editorial',
                'verbose_name_plural': 'comentários editoriais',
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['article', 'status', 'created_at'], name='editorial_e_article_111525_idx')],
            },
        ),
    ]
