# Generated by Django 5.2.17 on 2026-09-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0005_aviso_pauta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('review_requested', 'Revisão pedida'), ('changes_requested', 'Alterações sugeridas'), ('approved', 'Revisão aprovada'), ('published_by_other', 'Publicado por outra pessoa'), ('edited_by_other', 'Editado por outra pessoa'), ('archived_by_other', 'Arquivado por outra pessoa'), ('comment_pending', 'Comentário aguardando'), ('review_comment', 'Comentário na revisão'), ('review_stale', 'Revisão parada'), ('suggestions', 'Sugestões de pauta'), ('story_idea', 'Pauta'), ('account_pending', 'Conta aguardando aprovação'), ('account_approved', 'Conta aprovada'), ('system', 'Sistema')], max_length=24, verbose_name='tipo'),
        ),
    ]
