# Generated by Django 5.2.17 on 2026-09-17 14:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0003_area_color_magenta_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('feed_url', models.URLField(max_length=500, unique=True, verbose_name='endereço do feed')),
                ('site_url', models.URLField(blank=True, max_length=500, verbose_name='site')),
                ('kind', models.CharField(choices=[('rss', 'RSS ou Atom')], default='rss', max_length=10, verbose_name='tipo')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês')], default='pt', max_length=5, verbose_name='idioma')),
                ('trust_level', models.PositiveSmallIntegerField(default=3, help_text='De 1 a 5. Fontes com 2 ou menos só aparecem para quem pedir.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='confiança')),
                ('fetch_interval_minutes', models.PositiveIntegerField(default=120, validators=[django.core.validators.MinValueValidator(30)], verbose_name='intervalo entre coletas (minutos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('etag', models.CharField(blank=True, editable=False, max_length=300)),
                ('last_modified', models.CharField(blank=True, editable=False, max_length=100)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='última coleta')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='última coleta sem erro')),
                ('last_error', models.TextField(blank=True, verbose_name='último erro')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='hora do último erro')),
                ('consecutive_failures', models.PositiveIntegerField(default=0, verbose_name='falhas seguidas')),
                ('default_disciplines', models.ManyToManyField(blank=True, related_name='news_sources', to='taxonomy.discipline', verbose_name='disciplinas padrão')),
                ('default_topics', models.ManyToManyField(blank=True, help_text='Tudo o que vem desta fonte recebe estes tópicos na classificação.', related_name='news_sources', to='taxonomy.topic', verbose_name='tópicos padrão')),
            ],
            options={
                'verbose_name': 'fonte de notícias',
                'verbose_name_plural': 'fontes de notícias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=300, verbose_name='título')),
                ('url', models.URLField(db_index=True, max_length=1000, verbose_name='link do feed')),
                ('canonical_url', models.URLField(max_length=1000, verbose_name='link canônico')),
                ('url_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('title_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('summary', models.TextField(blank=True, max_length=600, verbose_name='resumo')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='imagem (só o endereço)')),
                ('published_at', models.DateTimeField(db_index=True, verbose_name='publicada em')),
                ('fetched_at', models.DateTimeField(verbose_name='coletada em')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês')], max_length=5, verbose_name='idioma')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='oculta')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='curation.newssource', verbose_name='fonte')),
            ],
            options={
                'verbose_name': 'notícia coletada',
                'verbose_name_plural': 'notícias coletadas',
                'ordering': ['-published_at'],
            },
        ),
    ]
