# Generated by Django 5.2.17 on 2026-09-28 18:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0001_initial'),
        ('taxonomy', '0003_area_color_magenta_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItemClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='score')),
                ('method', models.CharField(choices=[('source_default', 'Padrão da fonte'), ('keyword', 'Palavra-chave'), ('manual', 'Ajuste manual')], max_length=20, verbose_name='método')),
                ('matched', models.CharField(blank=True, help_text='Só no método palavra-chave.', max_length=300, verbose_name='palavras encontradas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_classifications', to='taxonomy.discipline', verbose_name='disciplina')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='curation.newsitem', verbose_name='notícia')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_classifications', to='taxonomy.topic', verbose_name='tópico')),
            ],
            options={
                'verbose_name': 'classificação de notícia',
                'verbose_name_plural': 'classificações de notícias',
                'ordering': ['-score'],
                'constraints': [models.CheckConstraint(condition=models.Q(('topic__isnull', True), ('discipline__isnull', True), _connector='XOR'), name='curation_classification_topic_xor_discipline'), models.UniqueConstraint(condition=models.Q(('topic__isnull', False)), fields=('item', 'topic', 'method'), name='curation_classification_unique_topic'), models.UniqueConstraint(condition=models.Q(('discipline__isnull', False)), fields=('item', 'discipline', 'method'), name='curation_classification_unique_discipline')],
            },
        ),
    ]
