# Generated by Django 5.2.17 on 2026-09-28 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0002_classificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('score', models.FloatField(verbose_name='score')),
                ('status', models.CharField(choices=[('suggested', 'Sugerida'), ('ignored', 'Ignorada'), ('saved', 'Salva'), ('interesting', 'Interessante'), ('converted', 'Virou pauta')], default='suggested', max_length=12, verbose_name='situação')),
                ('acted_at', models.DateTimeField(blank=True, help_text='Vazio quando a sugestão expirou sozinha: não conta como ignorar.', null=True, verbose_name='ação do professor em')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='curation.newsitem', verbose_name='notícia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='professor')),
            ],
            options={
                'verbose_name': 'sugestão de notícia',
                'verbose_name_plural': 'sugestões de notícias',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='curation_ne_user_id_17e836_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'item'), name='curation_recommendation_unique_user_item')],
            },
        ),
    ]
