# Generated by Django 5.2.17 on 2026-09-28 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0003_sugestoes'),
        ('publications', '0006_search'),
        ('taxonomy', '0003_area_color_magenta_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('notes', models.TextField(blank=True, max_length=2000, verbose_name='notas')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('assigned', 'Atribuída'), ('in_progress', 'Em produção'), ('done', 'Concluída')], db_index=True, default='open', max_length=12, verbose_name='situação')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_ideas', to='publications.article', verbose_name='publicação')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_story_ideas', to=settings.AUTH_USER_MODEL, verbose_name='com quem está')),
                ('disciplines', models.ManyToManyField(blank=True, related_name='story_ideas', to='taxonomy.discipline', verbose_name='disciplinas')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_ideas', to='curation.newsitem', verbose_name='notícia de origem')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_story_ideas', to=settings.AUTH_USER_MODEL, verbose_name='proposta por')),
                ('topics', models.ManyToManyField(blank=True, related_name='story_ideas', to='taxonomy.topic', verbose_name='tópicos')),
            ],
            options={
                'verbose_name': 'pauta',
                'verbose_name_plural': 'pautas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='newsrecommendation',
            name='story_idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='curation.storyidea', verbose_name='pauta'),
        ),
    ]
