# Generated by Django 5.2.17 on 2026-09-12 19:51

import apps.accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('full_name', models.CharField(max_length=150, verbose_name='nome completo')),
                ('display_name', models.CharField(blank=True, help_text='Como o nome aparece no site. Se vazio, usa o nome completo.', max_length=80, verbose_name='nome público')),
                ('role', models.CharField(choices=[('staff', 'Equipe'), ('editor', 'Editor'), ('admin', 'Administrador')], db_index=True, default='staff', help_text='Define o que a pessoa pode fazer no sistema.', max_length=10, verbose_name='papel')),
                ('staff_kind', models.CharField(choices=[('teacher', 'Professor'), ('monitor', 'Monitor'), ('coordinator', 'Coordenação'), ('principal', 'Direção'), ('librarian', 'Sala de leitura'), ('other', 'Outro')], default='teacher', help_text='Apenas para exibição; não dá permissões.', max_length=12, verbose_name='cargo')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para bloquear o acesso sem apagar a conta.', verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, editable=False, help_text='Calculado a partir do papel: só administradores.', verbose_name='acesso ao Django Admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='cadastrado em')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='desativado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['full_name'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
