# Generated by Django 5.2.17 on 2026-09-12 21:09

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('slug', models.SlugField(help_text='Parte final da URL do perfil. Mudar quebra links antigos.', max_length=90, unique=True, verbose_name='endereço do perfil')),
                ('headline', models.CharField(blank=True, help_text='Ex.: "Professora de Biologia", "Monitor escolar".', max_length=120, verbose_name='apresentação curta')),
                ('bio', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(800)], verbose_name='sobre mim')),
                ('education', models.JSONField(blank=True, default=apps.accounts.models._default_list, help_text='Lista de {degree, institution, year}.', verbose_name='formação')),
                ('since_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='na escola desde')),
                ('links', models.JSONField(blank=True, default=apps.accounts.models._default_list, help_text='Lista de {label, url}, até 4.', verbose_name='links')),
                ('accepts_english', models.BooleanField(default=True, verbose_name='aceita sugestões em inglês')),
                ('is_public', models.BooleanField(default=True, verbose_name='perfil público')),
                ('show_reviewer_credit', models.BooleanField(default=True, verbose_name='mostrar crédito como revisor')),
                ('reviewers_may_publish', models.BooleanField(default=False, verbose_name='revisores podem publicar por mim (padrão)')),
                ('show_reads', models.BooleanField(default=True, verbose_name='mostrar leituras nas minhas publicações')),
                ('areas', models.ManyToManyField(blank=True, related_name='profiles', to='taxonomy.knowledgearea', verbose_name='áreas de atuação')),
                ('disciplines', models.ManyToManyField(blank=True, related_name='profiles', to='taxonomy.discipline', verbose_name='disciplinas')),
                ('topics', models.ManyToManyField(blank=True, related_name='profiles', to='taxonomy.topic', verbose_name='interesses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
            },
        ),
        migrations.CreateModel(
            name='AccessLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='código')),
                ('purpose', models.CharField(choices=[('first_access', 'Primeiro acesso'), ('password_reset', 'Redefinir senha')], max_length=16, verbose_name='finalidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='gerado em')),
                ('expires_at', models.DateTimeField(verbose_name='expira em')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='usado em')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='gerado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_links', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'link de acesso',
                'verbose_name_plural': 'links de acesso',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'used_at', 'revoked_at'], name='accounts_ac_user_id_4a467f_idx')],
            },
        ),
    ]
