# Generated by Django 5.2.17 on 2026-09-14 19:55

from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def mark_existing_as_onboarded(apps, schema_editor):
    """Quem já entrou alguma vez não precisa ver o assistente de primeiro acesso."""
    TeacherProfile = apps.get_model("accounts", "TeacherProfile")
    User = apps.get_model("accounts", "User")
    last_login = User.objects.filter(pk=OuterRef("user_id")).values("last_login")[:1]
    TeacherProfile.objects.filter(user__last_login__isnull=False).update(
        onboarded_at=Subquery(last_login)
    )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="onboarded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Vazio: o próximo login leva ao assistente de primeiro acesso.",
                null=True,
                verbose_name="assistente de primeiro acesso concluído em",
            ),
        ),
        migrations.RunPython(mark_existing_as_onboarded, migrations.RunPython.noop),
    ]
