# Generated by Django 5.2.17 on 2026-09-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_profile_onboarded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="anonymized_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Dados pessoais apagados (docs/23). A conta não pode ser reativada.",
                null=True,
                verbose_name="anonimizado em",
            ),
        ),
    ]
