# Generated by Django 5.2.17 on 2026-09-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_anonymized_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='include_low_trust',
            field=models.BooleanField(default=False, help_text='Sugestões de fontes com confiança 1 ou 2 (docs/21).', verbose_name='inclui fontes de menor confiança'),
        ),
    ]
