# Generated by Django 5.2.17 on 2026-09-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_preferencia_fontes_menor_confianca'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='e-mail')),
                ('purpose', models.CharField(choices=[('signup', 'Cadastro'), ('password_reset', 'Nova senha')], max_length=16, verbose_name='finalidade')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='nome informado')),
                ('code_hash', models.CharField(editable=False, max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas erradas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('expires_at', models.DateTimeField(verbose_name='expira em')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='usado em')),
            ],
            options={
                'verbose_name': 'código por e-mail',
                'verbose_name_plural': 'códigos por e-mail',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Contas criadas pelo cadastro próprio esperam a aprovação de um editor (docs/27, quinta rodada). As criadas pelo admin nascem aprovadas.', verbose_name='aprovada'),
        ),
    ]
