# Generated by Django 5.2.17 on 2026-09-12 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='media/', verbose_name='arquivo')),
                ('variants', models.JSONField(blank=True, default=dict, help_text='{"w480": caminho, ...} em WebP', verbose_name='variantes')),
                ('width', models.PositiveIntegerField(verbose_name='largura')),
                ('height', models.PositiveIntegerField(verbose_name='altura')),
                ('size_bytes', models.PositiveIntegerField(verbose_name='tamanho (bytes)')),
                ('mime', models.CharField(max_length=32, verbose_name='tipo')),
                ('alt_text', models.CharField(blank=True, help_text='Descreve a imagem para quem não pode vê-la.', max_length=250, verbose_name='texto alternativo')),
                ('is_decorative', models.BooleanField(default=False, help_text='Imagem sem informação; dispensa texto alternativo.', verbose_name='decorativa')),
                ('credit', models.CharField(blank=True, max_length=120, verbose_name='crédito')),
                ('license', models.CharField(choices=[('own', 'Própria (da escola ou de quem publicou)'), ('cc-by', 'Creative Commons BY'), ('cc-by-sa', 'Creative Commons BY-SA'), ('public-domain', 'Domínio público'), ('authorized', 'Uso autorizado pelo autor')], default='own', max_length=16, verbose_name='licença')),
                ('has_people', models.BooleanField(default=False, verbose_name='aparecem pessoas')),
                ('consent_ok', models.BooleanField(default=False, help_text='Quem publicou declara ter autorização das pessoas que aparecem.', verbose_name='autorização de imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='enviada em')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to=settings.AUTH_USER_MODEL, verbose_name='enviada por')),
            ],
            options={
                'verbose_name': 'imagem',
                'verbose_name_plural': 'imagens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['uploaded_by', 'created_at'], name='publication_uploade_3696cf_idx')],
            },
        ),
    ]
