# Generated by Django 5.2.17 on 2026-09-12 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(default='Sem título', max_length=120, verbose_name='título')),
                ('subtitle', models.CharField(blank=True, max_length=220, verbose_name='linha fina')),
                ('slug', models.SlugField(blank=True, help_text='Gerado na primeira publicação e nunca muda.', max_length=140, null=True, unique=True, verbose_name='endereço')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], db_index=True, default='draft', max_length=20, verbose_name='estado')),
                ('body_json', models.JSONField(blank=True, default=dict, verbose_name='corpo (documento do editor)')),
                ('body_html', models.TextField(blank=True, verbose_name='corpo em HTML')),
                ('body_text', models.TextField(blank=True, verbose_name='corpo em texto')),
                ('cover_caption', models.CharField(blank=True, max_length=200, verbose_name='legenda da capa')),
                ('event_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='data do evento')),
                ('event_location', models.CharField(blank=True, max_length=120, verbose_name='local do evento')),
                ('sources', models.JSONField(blank=True, default=list, help_text='Lista de {title, url, publisher}.', verbose_name='fontes')),
                ('reading_minutes', models.PositiveSmallIntegerField(default=1, verbose_name='minutos de leitura')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='destaque na home')),
                ('featured_order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ordem do destaque')),
                ('comments_enabled', models.BooleanField(default=True, verbose_name='comentários ligados')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado para revisão em')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='arquivado em')),
                ('reads_count', models.PositiveIntegerField(default=0, verbose_name='leituras')),
                ('reactions_count', models.JSONField(blank=True, default=dict, verbose_name='reações')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='comentários aprovados')),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='publications.mediaasset', verbose_name='capa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_articles', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('disciplines', models.ManyToManyField(blank=True, related_name='articles', to='taxonomy.discipline', verbose_name='disciplinas')),
                ('topics', models.ManyToManyField(blank=True, related_name='articles', to='taxonomy.topic', verbose_name='tópicos')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='taxonomy.articletype', verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'publicação',
                'verbose_name_plural': 'publicações',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='publications.article', verbose_name='publicação'),
        ),
        migrations.CreateModel(
            name='ArticleContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Para membros da equipe, copiado do perfil no momento do crédito.', max_length=80, verbose_name='nome no crédito')),
                ('role', models.CharField(choices=[('author', 'Autor'), ('coauthor', 'Coautor'), ('collaborator', 'Colaboração'), ('reviewer', 'Revisão'), ('editor', 'Edição')], default='author', max_length=16, verbose_name='papel')),
                ('is_student', models.BooleanField(default=False, verbose_name='aluno')),
                ('class_group', models.CharField(blank=True, help_text='Ex.: "2ª série B"', max_length=20, verbose_name='turma')),
                ('consent_ok', models.BooleanField(default=False, help_text='Declaro ter autorização do responsável para publicar o nome do aluno.', verbose_name='autorização')),
                ('contribution_note', models.CharField(blank=True, help_text='Ex.: "fotos", "entrevista"', max_length=80, verbose_name='contribuição')),
                ('can_publish', models.BooleanField(default=False, verbose_name='pode publicar pelo autor')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('show_in_credits', models.BooleanField(default=True, verbose_name='mostrar nos créditos')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='publications.article', verbose_name='publicação')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL, verbose_name='membro da equipe')),
            ],
            options={
                'verbose_name': 'crédito',
                'verbose_name_plural': 'créditos',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ArticleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='número')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('subtitle', models.CharField(blank=True, max_length=220, verbose_name='linha fina')),
                ('body_json', models.JSONField(default=dict, verbose_name='corpo')),
                ('reason', models.CharField(choices=[('published', 'Publicação'), ('submitted', 'Envio para revisão'), ('edited_after_publish', 'Edição depois de publicado'), ('manual', 'Manual')], max_length=24, verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='feita em')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='publications.article', verbose_name='publicação')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='feita por')),
            ],
            options={
                'verbose_name': 'versão',
                'verbose_name_plural': 'versões',
                'ordering': ['article', '-number'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-published_at'], name='article_status_published'),
        ),
        migrations.AddIndex(
            model_name='articlecontributor',
            index=models.Index(fields=['user', 'role'], name='publication_user_id_642c18_idx'),
        ),
        migrations.AddConstraint(
            model_name='articlecontributor',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('article', 'user', 'role'), name='contributor_unique_user_role'),
        ),
        migrations.AddConstraint(
            model_name='articlecontributor',
            constraint=models.CheckConstraint(condition=models.Q(('is_student', False), ('user__isnull', True), _connector='OR'), name='contributor_student_has_no_user'),
        ),
        migrations.AddConstraint(
            model_name='articlerevision',
            constraint=models.UniqueConstraint(fields=('article', 'number'), name='revision_unique_number'),
        ),
    ]
