# Generated by Django 5.2.17 on 2026-09-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_article_last_edited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('in_review', 'Em revisão'), ('changes_requested', 'Alterações sugeridas'), ('published', 'Publicado'), ('archived', 'Arquivado')], db_index=True, default='draft', max_length=20, verbose_name='estado'),
        ),
    ]
