# Generated by Django 5.2.17 on 2026-09-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0004_alter_article_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlecontributor",
            name="anonymized_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Nome do aluno trocado por crédito genérico (docs/23).",
                null=True,
                verbose_name="anonimizado em",
            ),
        ),
    ]
