# Generated by Django 5.2.17 on 2026-09-15 01:14
"""Busca (E35, docs/19).

1. Extensões `unaccent` e `pg_trgm` (confiáveis desde o PostgreSQL 13: o dono do banco cria).
2. `f_unaccent(text)`: unaccent marcada como IMMUTABLE, para poder ser usada em índices.
3. Configuração de busca `pt_unaccent`: cópia da `portuguese` que tira os acentos antes de
   reduzir a palavra ao radical ("Física" e "fisica" viram "fisic").
4. Campos `search_meta` e `search_vector` com índice GIN, e o preenchimento das publicações
   que já existem (o mesmo que `manage.py reindex_search` faz).

Tudo com IF NOT EXISTS / OR REPLACE: rodar de novo num banco que já tem as peças não quebra.
"""

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations, models

CREATE_F_UNACCENT = """
CREATE OR REPLACE FUNCTION public.f_unaccent(text) RETURNS text
LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT
AS $func$ SELECT public.unaccent('public.unaccent'::regdictionary, $1) $func$;
"""

CREATE_PT_UNACCENT = """
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_ts_config WHERE cfgname = 'pt_unaccent') THEN
        CREATE TEXT SEARCH CONFIGURATION public.pt_unaccent (COPY = pg_catalog.portuguese);
    END IF;
END
$$;
ALTER TEXT SEARCH CONFIGURATION public.pt_unaccent
    ALTER MAPPING FOR hword, hword_part, word WITH public.unaccent, portuguese_stem;
"""


def fill_search_vectors(apps, schema_editor):
    """Cópia congelada de apps/publications/search.py (migrações não importam o código atual)."""
    from django.contrib.postgres.search import SearchVector
    from django.db.models import TextField, Value

    Article = apps.get_model("publications", "Article")
    ArticleContributor = apps.get_model("publications", "ArticleContributor")
    config = "pt_unaccent"
    for article in Article.objects.all().iterator():
        names = [
            *article.disciplines.order_by("name").values_list("name", flat=True),
            *article.topics.order_by("name").values_list("name", flat=True),
            *ArticleContributor.objects.filter(article=article, show_in_credits=True)
            .order_by("order", "pk")
            .values_list("display_name", flat=True),
        ]
        meta = " · ".join(name for name in names if name)
        vector = (
            SearchVector("title", weight="A", config=config)
            + SearchVector("subtitle", weight="B", config=config)
            + SearchVector(Value(meta, output_field=TextField()), weight="B", config=config)
            + SearchVector("body_text", weight="C", config=config)
        )
        Article.objects.filter(pk=article.pk).update(search_meta=meta, search_vector=vector)


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_articlecontributor_anonymized_at'),
        ('taxonomy', '0002_area_short_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        UnaccentExtension(),
        TrigramExtension(),
        migrations.RunSQL(
            CREATE_F_UNACCENT, reverse_sql="DROP FUNCTION IF EXISTS public.f_unaccent(text);"
        ),
        migrations.RunSQL(
            CREATE_PT_UNACCENT,
            reverse_sql="DROP TEXT SEARCH CONFIGURATION IF EXISTS public.pt_unaccent;",
        ),
        migrations.AddField(
            model_name='article',
            name='search_meta',
            field=models.TextField(blank=True, editable=False, help_text='Disciplinas, tópicos e créditos concatenados (apps/publications/search.py).', verbose_name='nomes para a busca'),
        ),
        migrations.AddField(
            model_name='article',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True, verbose_name='índice de busca'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='article_search_vector'),
        ),
        migrations.RunPython(fill_search_vectors, migrations.RunPython.noop),
    ]
