# Generated by Django 5.2.17 on 2026-09-28 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0004_pautas'),
        ('publications', '0006_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='origin_news_item',
            field=models.ForeignKey(blank=True, help_text='Preenchida quando o rascunho nasce de uma pauta (docs/21).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_articles', to='curation.newsitem', verbose_name='notícia de origem'),
        ),
    ]
