# Generated by Django 5.2.17 on 2026-09-12 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, help_text='Usado na URL. Se vazio, é gerado a partir do nome.', max_length=80, unique=True, verbose_name='endereço')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Menor aparece primeiro.', verbose_name='ordem')),
                ('has_event_date', models.BooleanField(default=False, help_text='Publicações deste tipo precisam informar quando o evento acontece.', verbose_name='exige data do evento')),
            ],
            options={
                'verbose_name': 'tipo de publicação',
                'verbose_name_plural': 'tipos de publicação',
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, help_text='Usado na URL. Se vazio, é gerado a partir do nome.', max_length=80, unique=True, verbose_name='endereço')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Menor aparece primeiro.', verbose_name='ordem')),
                ('color', models.CharField(choices=[('coral', 'Coral'), ('verde', 'Verde'), ('azul', 'Azul'), ('ambar', 'Âmbar'), ('violeta', 'Violeta'), ('petroleo', 'Petróleo'), ('magenta', 'Magenta (reservada)'), ('grafite', 'Grafite (geral)')], default='grafite', help_text='Cor usada em etiquetas, cards e no cabeçalho da área.', max_length=16, verbose_name='cor')),
            ],
            options={
                'verbose_name': 'área do conhecimento',
                'verbose_name_plural': 'áreas do conhecimento',
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, help_text='Usado na URL. Se vazio, é gerado a partir do nome.', max_length=80, unique=True, verbose_name='endereço')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Menor aparece primeiro.', verbose_name='ordem')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplines', to='taxonomy.knowledgearea', verbose_name='área')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
                'ordering': ['area__order', 'order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, help_text='Usado na URL. Se vazio, é gerado a partir do nome.', max_length=80, unique=True, verbose_name='endereço')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Termos usados para classificar notícias (Fase 4).', verbose_name='palavras-chave')),
                ('disciplines', models.ManyToManyField(blank=True, related_name='topics', to='taxonomy.discipline', verbose_name='disciplinas sugeridas')),
            ],
            options={
                'verbose_name': 'tópico',
                'verbose_name_plural': 'tópicos',
                'ordering': ['name'],
            },
        ),
    ]
