# Generated by Django 5.2.17 on 2026-09-12 23:54

from django.db import migrations, models

# Nomes curtos das áreas criadas pelo seed_taxonomy (valores fixos: a migração não deve
# depender do seed_data, que pode mudar depois).
SHORT_NAMES = {
    "linguagens": "Linguagens",
    "matematica": "Matemática",
    "ciencias-da-natureza": "Natureza",
    "ciencias-humanas": "Humanas",
    "formacao-e-projetos": "Projetos",
    "escola-e-comunidade": "Comunidade",
}


def fill_short_names(apps, schema_editor):
    KnowledgeArea = apps.get_model("taxonomy", "KnowledgeArea")
    for slug, short_name in SHORT_NAMES.items():
        KnowledgeArea.objects.filter(slug=slug, short_name="").update(short_name=short_name)


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgearea",
            name="short_name",
            field=models.CharField(
                blank=True,
                help_text='Usado no menu do cabeçalho, ex.: "Natureza". Se vazio, usa o nome.',
                max_length=30,
                verbose_name="nome curto",
            ),
        ),
        migrations.RunPython(fill_short_names, migrations.RunPython.noop),
    ]
