# Generated by Django 5.2.17 on 2026-09-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_area_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgearea',
            name='color',
            field=models.CharField(choices=[('coral', 'Coral'), ('verde', 'Verde'), ('azul', 'Azul'), ('ambar', 'Âmbar'), ('violeta', 'Violeta'), ('petroleo', 'Petróleo'), ('magenta', 'Magenta'), ('grafite', 'Grafite (geral)')], default='grafite', help_text='Cor usada em etiquetas, cards e no cabeçalho da área.', max_length=16, verbose_name='cor'),
        ),
    ]
